# preload
preload = $HOME/.dotfiles/data/dot_wallpaper/wallpaper_dark.png

# wallpaper
wallpaper = DP-1,$HOME/.dotfiles/data/dot_wallpaper/wallpaper_dark.png
wallpaper = DP-3,$HOME/.dotfiles/data/dot_wallpaper/wallpaper_dark.png

# conf
splash = true
ipc = on
