###################
### MY PROGRAMS ###
###################
# default programs for apps
$terminal = ghostty
$fileManager = nautilus
$menu = rofi -show drun

###################
### PERMISSIONS ###
###################
# configure app permissions (screencap, plugins);
# ecosystem {
#   enforce_permissions = 1
# }
#
# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
#
# #############
# ### DEBUG ###
# #############
# debug:disable_logs = false  # keep logs enabled for crash debugging
