#############
### INPUT ###
#############
cursor {
    no_hardware_cursors = false
    sync_gsettings_theme = true
}

env = WLR_NO_HARDWARE_CURSORS,1

# configure keyboard, mouse, and touchpad input settings
input {
    kb_layout = pl
    kb_variant =
    kb_model = pc105
    kb_options =
    kb_rules =

    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

