##############################
### WINDOWS AND WORKSPACES ###
##############################
# define basic window rules (maximize behavior, focus handling)
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

###############################
### LAYOUT-SPECIFIC OPTIONS ###
###############################
# layout behavior for dwindle and master
dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

# misc settings (wallpaper and logo)
misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

