##############################
### WINDOWS AND WORKSPACES ###
##############################
# define basic window rules (maximize behavior, focus handling)
windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$, match:title ^$, match:xwayland on, match:float on, match:fullscreen off, match:pin off, no_focus on

windowrule = match:class ^(cs2)$, match:fullscreen on

workspace = 9, monitor:DP-3, default:true, persistent:true

windowrule = match:class ^(discord)$, workspace 9 silent
windowrule = match:class ^([Ss]potify)$, workspace 9 silent
windowrule = match:class ^(discord)$, monitor DP-3
windowrule = match:class ^([Ss]potify)$, monitor DP-3

###############################
### LAYOUT-SPECIFIC OPTIONS ###
###############################
# layout behavior for dwindle and master
dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

# misc settings (wallpaper and logo)
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

