##############################
### WINDOWS AND WORKSPACES ###
##############################
# define basic window rules (maximize behavior, focus handling)
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrulev2 = fullscreen, class:^(cs2)$
windowrulev2 = immediate, class:^(cs2)$

workspace = 9, monitor:DP-3, default:true, persistent:true

windowrulev2 = workspace 9 silent, class:^(discord)$
windowrulev2 = workspace 9 silent, class:^([Ss]potify)$
windowrulev2 = monitor DP-3, class:^(discord)$
windowrulev2 = monitor DP-3, class:^([Ss]potify)$

###############################
### LAYOUT-SPECIFIC OPTIONS ###
###############################
# layout behavior for dwindle and master
dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

# misc settings (wallpaper and logo)
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}

