#################
### AUTOSTART ###
#################
# apps and services to start automatically with Hyprland
exec-once = hyprpanel
exec-once = hyprpaper
exec-once = mako

exec-once = sudo systemctl start docker

# portals and authentication agents
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = /usr/lib/xdg-desktop-portal
exec-once = hyprpolkitagent

# apps on workspace 2
exec-once = [workspace 2] discord
exec-once = [workspace 2] spotify-launcher