#################
### AUTOSTART ###
#################
# apps and services to start automatically with Hyprland
exec-once = sleep 1 && hyprctl dismissnotify -1
exec-once = hyprpanel

exec-once = swww-daemon
exec-once = swww img $HOME/.dotfiles/data/dot_wallpaper/wallpaper_dark.png

exec-once = hyprctl setcursor Dracula-cursors 24

exec-once = sleep 1 && hyprctl dispatch workspace 9 && sleep 1 && hyprctl dispatch exec [workspace 9 silent] spotify && sleep 2 && hyprctl dispatch exec [workspace 9 silent] discord && sleep 3 && hyprctl dispatch workspace 1