##############################
### WINDOWS AND WORKSPACES ###
##############################
# define basic window rules (maximize behavior, focus handling)
windowrule = suppressevent maximize, class:.*
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

#############
### RULES ###
#############
# specific window rules (workspace assignment, size, opacity)
windowrulev2 = workspace 2, class:^(com.mitchellh.ghostty)$,title:^(.*nvim.*)$
windowrulev2 = workspace 2, class:^(discord)$
windowrulev2 = workspace 2, class:^(Spotify)$

windowrulev2 = size 1200 800, class:^(discord)$
windowrulev2 = size 800 600, class:^(spotify)$
windowrulev2 = size 800 600, class:^(com.mitchellh.ghostty)$

windowrulev2 = opacity 0.50, class:^(ghostty)$

###############################
### LAYOUT-SPECIFIC OPTIONS ###
###############################
# layout behavior for dwindle and master
dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

# misc settings (wallpaper and logo)
misc {
    force_default_wallpaper = -1
    disable_hyprland_logo = false
}

