#################
### AUTOSTART ###
#################
# apps and services to start automatically with Hyprland
exec-once = waybar
exec-once = hyprpaper
exec-once = mako

# portals and authentication agents
exec-once = /usr/lib/xdg-desktop-portal-hyprland
exec-once = hyprpolkitagent

# apps on workspace 2
exec-once = [workspace 2 silent;] ghostty -e nvim ~/.dotfiles/data/notes/my_notes.md
exec-once = [workspace 2 silent;] discord
exec-once = [workspace 2 silent;] spotify

