# -------------------
# 0. Hyprland Config
# -------------------
source=~/.config/hypr/conf/00-base.conf
source=~/.config/hypr/conf/10-outputs.conf
source=~/.config/hypr/conf/20-inputs.conf
source=~/.config/hypr/conf/30-keybinds.conf
source=~/.config/hypr/conf/40-windows.conf
source=~/.config/hypr/conf/50-exec.conf
source=~/.config/hypr/conf/60-ui.conf