# -------------------
# 0. Hyprland Config
# -------------------
source=~/.config/hypr/hyprland/00-base.conf
source=~/.config/hypr/hyprland/10-outputs.conf
source=~/.config/hypr/hyprland/20-inputs.conf
source=~/.config/hypr/hyprland/30-keybinds.conf
source=~/.config/hypr/hyprland/40-windows.conf
source=~/.config/hypr/hyprland/50-exec.conf
source=~/.config/hypr/hyprland/60-ui.conf