env = HYPRLAND_NO_SD_VARS,1

exec-once = sleep 0.3 && hyprctl dismissnotify -1
exec-once = regreet; hyprctl dispatch exit

monitor = DP-1, 1920x1080@144, 0x0, 1
monitor = *, disable

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Dracula-cursors

exec-once = hyprctl setcursor Dracula-cursors 24

env = GTK_USE_PORTAL,0
env = GDK_DEBUG,no-portals

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}