exec-once = regreet; hyprctl dispatch exit

env = XCURSOR_SIZE,24
env = XCURSOR_THEME,Dracula-cursors

exec-once = hyprctl setcursor Dracula-cursors 24

env = GTK_USE_PORTAL,0
env = GDK_DEBUG,no-portals

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}