[background]
path = "/usr/share/backgrounds/greeter.png"
fit = "Cover"

[env]
ENV_VARIABLE = "value"

[GTK]
application_prefer_dark_theme = true
font_name = "JetBrainsMono Nerd Font 12"
css_file_path = "/etc/greetd/regreet.css"

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]

[appearance]
greeting_msg = "Welcome back in Greeter!"

[widget.clock]
format = "%a %H:%M"
resolution = "1s"
timezone = "Europe/Warsaw"
label_width = 150

